### ISSUE TITLE
Open / close dropdown on hover

### ISSUE THREAD

**Issue by toketeeman** [kekeh/vsdropdown#1]
I would like to be able to use ng-mouseover and ng-mouseleave on the vsdropdown element to dynamically open and close the dropdown, respectively. It looks like I need to execute your openOverlay() and closeOverlay() functions. Is this possible?

**Comment by kekeh** [comment]
openOverlay() show all selections. If you want to open/close dropdown do it this way:
ng-mouseenter="selector()"
ng-mouseleave="selector()"

**Comment by toketeeman** [comment]
Excellent! Thank you very much. 
  
Dwight Spencer ("toketeeman") 
  
Portland, Oregon 

----- Original Message -----

**Comment by toketeeman** [comment]
Now at work. Both of my bugs are still present. 
  
First, the scrolling works fine on http://kekeh.github.io/vsdropdown/  but does not work on my dropdown as I have described. I am using IE 11. Also, 
I am loading approximately 600 options into it. 
  
Second, the dropdown still does not open on hover (I tried IE 11 and Chrome). 
  
I show my html and configuration below. Please advise on any errors I have made. 
  
  
    <div class="row"> 
        <div class="col-md-4 col-md-offset-4"> 
            <vsdropdown options="assignments.levelOneProjectsDDOptions" ng-mouseenter="selector()" ng-mouseleave="selector()"></vsdropdown> 
        </div> 
    </div>  
  
This is the dropdown's configuration within the controller (the parent controller is being aliased as "assignments"): 
  
        // Configure level one projects dropdown. 
        thisController.levelOneProjectsDDOptions = { 
            items: thisController.allLevelOneProjects, 
            selectedItems: thisController.selectedLevelOneProject, 
            input: { 
                isObject: true, 
                visiblePropName: 'LONG_PROJECT_NAME', 
                properties: { 
                    enabled: false, 
                    propertyTitle: "", 
                    valueTitle: "" 
                } 
            }, 
            filter: { 
                enabled: false, 
                filterPlaceholderTxt: "", 
                noHitsTxt: "" 
            }, 
            selection: { 
                maximum: 1 
            }, 
            visibleItemCount: 20, 
            showTooltip: false, 
            fadeinEffects: true, 
            itemSelectCb: thisController.handleSelectedLevelOneProject 
        }; 
  
Other than these two bugs, the dropdown appears to work correctly. 
  
Thanks for your help. 
  
- Dwight Spencer ("toketeeman") 
  

----- Original Message -----

**Comment by kekeh** [comment]
1) The ng-mouseenter and ng-mouseleave are not attributes of vsdropdown tag. In order to get hover work, you have to add them to this template (https://github.com/kekeh/vsdropdown/blob/master/templates/vsdropdown/vsdropdown.html). For example line 11 have dropdown open button. Add ng-mouseenter="selector()" to line 11.

After editing templates, you have to build the project using grunt. Just type grunt to command line and a new build is created to the "dist" folder.

2) Your configuration seems to be ok. Can you create simple plunker (https://plnkr.co/) here and try to reproduce error there.

Here are also sample configurations of dropdown: https://github.com/kekeh/vsdropdown/blob/master/examples/sampleapp.js

**Comment by toketeeman** [comment]
Thanks. I am working exclusively in the Visual Studio ASP.NET world, so I had misunderstood you. 
  
I will pick up some grunt expertise to follow through on the hover solution. 
  
I will also try your plunker suggestion. 
  
Finally, I now wonder it there is some Visual Studio environmental problem with the scrolling. Frankly, I would recommend that you try your vsdropdown in Visual Studio within a MVC web app and see if the problem persists. There certainly are a lot of VS developers who could make good use of your dropdown. 
  
Thanks very much for your help. 
  
- Dwight Spencer

**Comment by toketeeman** [comment]
Here's the correction for the scrolling failure n vsdropdown for IE 11: 
  





function onScrollMouseWheel(evt) { 

  var event = window.event || evt; 

    event.preventDefault(); 

  var isDown = (event.wheelDelta || -event.detail) <= 0; 

    indexChange(isDown ? itemsInPage : -itemsInPage); 

} 




  

- Dwight Spencer 





  
  
  

----- Original Message -----

**Comment by toketeeman** [comment]
Here's the mods to have a smart auto expand/contract on mousenter/mouseleave: 

  

  

In vsdropdown-0.1.0.js: 

  

// NOTE: this function was added by Dwight Spencer. 
scope.leaveSelector = function () { 
    if (scope.showSelector) { 
    scope.showSelector = !scope.showSelector; 
    } 
}; 


// NOTE: this function was modified by Dwight Spencer. 
scope.selector = function () { 
    if (scope.showSelector) return; 
    scope.showSelector = !scope.showSelector; 
    if (scope.showSelector) { 
        scope.listFocusEvent(); 
        scope.focusIdx = 0; 
    } 
}; 

  


In vsdropdown.html: 

  

<div class="vsdropdown" ng-click="$event.stopPropagation()" ng-mouseenter="selector()" ngmouseleave="leaveSelector()" ng-style="{'border-radius':showSelector?'2px 2px 0 0':'2px'}"> 
  
  
Thanks, 
  
- Dwight Spencer 
  
  
  

----- Original Message -----
