### ISSUE TITLE
Scroll wheel always forces scrolling upward

### ISSUE THREAD

**Issue by toketeeman** [kekeh/vsdropdown#2]
When the dropdown is open with its options, instead of dragging the scroll bar up and down, I would like to move the mouse scroll wheel over the dropdown options area to scroll up and down. However no matter which direction I am moving the wheel, the scroll position always moves upward towards the first option. Once the scroll position reaches the first option, the scroll position will no longer move. Can this be fixed?

**Comment by kekeh** [comment]
Are you able reproduce error here: http://kekeh.github.io/vsdropdown/

In my test mouse wheel scroll works well also if options are open. I tested with Chrome and Firefox. What browser you are using?

**Comment by toketeeman** [comment]
Thanks for your prompt reply. Your virtualized dropdown is very well done and excellent for our large option lists that we often use. 
  
Unfortunately, it's Saturday and I will not be into work to re-check things properly until Monday morning. 
  
Nevertheless, both there and here at home I use IE 11. From home, IE 11 works fine for http://kekeh.github.io/vsdropdown/  . 
  
I will re-check it again at work on Monday and look at your test code. If it still fails, I will send you my options object and any other info I can think of. 
  
Also, I had simply installed only your dist folder .js and .css files into my ASP.NET MVC project within Visual Studio into the usual folders. 
  
Thanks again. 
  
  
Dwight Spencer ("toketeeman") 
  
Portland, Oregon 

----- Original Message -----

**Comment by zombiehugs** [comment]
Can also confirm scrolling issue with vsdropdown version 0.1.0, this occurs when scroll within IE11 as well as Chrome 47.0.2526.106. The demos on the your site and here however do not have this problem within the browsers mentioned above.

**Comment by toketeeman** [comment]
I have already supplied the solution to the scrolling problem with IE 11 earlier today. 
Thanks for the info. 
  
  
Dwight Spencer ("toketeeman") 

----- Original Message -----

**Comment by zombiehugs** [comment]
Saw this a little late. I have made changes in my solution by using the originalEvent property when co-existing with jQuery. I tried making a branch to submit a pull request. For anyone who stumbles across this, you can fix the problem within the vsscrollbar.js directive file.

Change out the onScrollMouseWheel to the following code.

```javascript
            function onScrollMouseWheel(event) {
                event.preventDefault();
                var isDown = false;
                (!window.jQuery) ? isDown = (event.wheelDelta || -event.detail) <= 0 : isDown = (event.originalEvent.wheelDelta || -event.originalEvent.detail) <= 0;
                indexChange(isDown ? itemsInPage : -itemsInPage);
            }
```

**Comment by kekeh** [comment]
Thanks a lot both of you. I will fix that IE related scrolling problem without jQuery.

**Comment by toketeeman** [comment]
Yes, I hope vsdropdown gets firmly stable and usably flexible because it is one of the very few excellent virtualizing dropdowns out there right now. 
Thanks, 
  
- Dwight Spencer 

----- Original Message -----

**Comment by kekeh** [comment]
Fixed IE related mouse wheel issue.

**Comment by zombiehugs** [comment]
No problem and thanks, enjoying the library thus far.

**Comment by toketeeman** [comment]
Is there any way to disable the scrollbar and have the dropdown display the entire selection list in the natural default way? 

  

For example, if I have a short item list of 6 objects, I simply want the dropdown to display a select list of 6 elements without any scrollbar and visibleItemCount is NOT specified. 

  

This feature would greatly enhance the usability of this control. 

  

Thanks, 

  

- Dwight Spencer ("toketeeman") 

----- Original Message -----

**Comment by kekeh** [comment]
It is not possible using current configuration. But setting this:  scope.scrollbarVisible = true; to false should hide the scrollbar. Not big task to add this kind of option to the configuration. Are you willing to do that ;-)

**Comment by toketeeman** [comment]
I am tempted to do that ... ;-) ... I'll think about it. I am building an actual enterprise web site, and I do have to watch the project schedule. 
------------------------------------------------------------------------------------------------------------------------ 
  
Yet another question: I would like to put a vsdropdown into a column filter for an angular ui-grid. 
  
I am using a headerCellTemplate (the standard default one published on github), and trying to insert 
  
      <vsdropdown options="grid.appScope.options"></vsdropdown> 
  
into it at an appropriate spot as recommended by various people who have inserted dropdowns as column filters. 
  
The vsdropdown does appear, but when it expands, its overflow is contained within the small column header area, hiding most of the expanded dropdown. 
I have tried applying overflow:visible and overflow:auto everywhere I can think of, but I cannot get the entire expanded dropdown to appear 
outside the column header area over the ui-grid window. 
  
However, an ordinary simple <select> dropdown does expand over the grid correctly! 
  
Would you have any idea why the overflow of vsdropdown is not visible in this situation? Or how that can be corrected? 
  
Thanks for all your help. 
  
- Dwight Spencer ("toketeeman") 
  







----- Original Message -----

**Comment by kekeh** [comment]
You can control visibility by overflow and z-index. Probably you need to change these from the ui-grid css. select is natiive component of the browser.

**Comment by toketeeman** [comment]
Good suggestion (underlined in red). I was changing overflow and z-index only on the vsdropdown components. Will give it a try. 
Thanks, 
  
Dwight Spencer ("toketeeman") 
  
----- Original Message -----

**Comment by toketeeman** [comment]
I have started to look towards adding of a couple of options to vsdropdown that would be particularly useful to me:  (1) removal of scrollbar and (2) providing a handler when closing the editing (i.e. when clicking on the 'X'). 
However my initial attempts seem to not be able to correctly introduce a new option property. I see the check !angular.isUndefined(scope.options.myOption) failing for me. Any suggestion on what the implementation process should be? 
  
Thanks for any help. 
  
- Dwight Spencer 

----- Original Message -----

**Comment by kekeh** [comment]
Options are now available only vsdropdown directive (https://github.com/kekeh/vsdropdown/blob/master/js/vsdropdown/directive/vsdropdown.js). You have to pass scrollbarvisible option to vsscrollbar directive. Add option attribute to <vsscrollbar> tag. It is located in templates/vsdropdown.html file.

**Comment by toketeeman** [comment]
Thank you for the info on options. 
  
------------------------------------------------------------------------------- 
  
Unfortunately, I have hit another problem that has completely puzzled me. I will offer the info in case you might have some idea. 
  
Scenario: 
  
1. Do $http call to server to get back a small array of objects:  (these are the actual objects that are assigned) 
  
      [{ pm_empl_id : "-ALL-", pm_name: "-ALL-"}, 
       { pm_empl_id: "00456", pm_name: "John Smith" }] 
  
2. The options.items of the dropdown is assigned this value. 
  
3. I open the dropdown and see the selections correctly for pm_name. 
  
4. I then do another $http call to server to get another small array of objects: 
  
      [{ pm_empl_id : "-ALL-", pm_name: "-ALL-"}, 
       { pm_empl_id: "00123", pm_name: "Frank Brown" }] 
  
5. The options.items of the dropdown is assigned this second array. (I have verified this second array is correct.) 
  
6.  I open the dropdown again BUT now see only the previous selections showing John Smith! 
  
7. All further $http's produce the same result. Only the first-loaded selections are shown by the vsdropdown! 
  
This only happens to one particular options configuration for this particular format of objects: 
  


       // Configure PM dropdown filter. 

       thisController.dropdownFilterPMOptions = { 

           items: [], 

           selectedItems: thisController.selectedFilterPM, 

           input: { 

               isObject: true , 

               visiblePropName: 'pm_name' , 

               properties: { 

                   enabled: false , 

                   propertyTitle: "" , 

                   valueTitle: "" 

               } 

           }, 

           filter: { 

               enabled: false , 

               filterPlaceholderTxt: "" , 

               noHitsTxt: "" 

           }, 

           selection: { 

               maximum: 1 

           }, 

           visibleItemCount: 10, 

           showTooltip: false , 

           fadeinEffects: false , 

           itemSelectCb: thisController.handleSelectedFilterPM 

       }; 

How is it possible that the vsdropdown would reject a new setting of the items and keep on showing the first setting? 
  
I have other very similar vsdropdowns on the page under the same scope with identical options configurations as this one but they 
all work CORRECTLY in this scenario. Only this one fails. 
  
I have tried a multiple of combinations and switching-arounds in the application js and html, but the bug follows this configuration and this data. 
  
Is there a way to programmatically refresh the dropdown? Is there something uniquely wrong with this configuration or unusual about the data? 
  
  
Thanks for any suggestions. 
  
- Dwight Spencer 
  
  
  
  
  
  
----- Original Message -----

**Comment by kekeh** [comment]
You can try to scope.$apply() to refresh.

**Comment by toketeeman** [comment]
Hello Kekeh, 
  
Just a simple question: what is a good way to programmatically reset or re-initialize a vsdropdown to its initlal unselected or no-selection state? Obviously it may already have a selection currently pending. 
  
Thanks for any assistance, 
  
- Dwight Spencer 
  
Portland, Oregon 
toketeeman@comcast.net 
  

----- Original Message -----
